version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: telegram_file_storage_db
    restart: always
    environment:
      POSTGRES_USER: telegram_user
      POSTGRES_PASSWORD: telegram_password
      POSTGRES_DB: telegram_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: